name: reunicorn
description: Where & how to get in contact, shared securely and privately.
publish_to: 'none'
version: "0.2.6+72"

environment:
  sdk: '>=3.8.0 <4.0.0'
  flutter: ">=3.38.0"

dependencies:
  ansicolor: ^2.0.3
  background_fetch: ^1.5.0
  bloc: ^9.0.1
  bloc_advanced_tools: ^0.1.13
  charcode: ^1.4.0
  collection: ^1.19.1
  equatable: ^2.0.7
  fast_immutable_collections: ^11.0.4
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_contacts: ^1.1.9
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.2.1
  formz: ^0.8.0
  freezed_annotation: ^3.1.0
  geolocator: ^14.0.2
  go_router: ^16.2.4
  image_picker: ^1.2.0
  intl: any
  image: ^4.5.4
  json_annotation: ^4.9.0
  latlong2: ^0.9.1
  loggy: ^2.0.3
  mobile_scanner: ^7.1.2
  path: ^1.9.1
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  provider: ^6.1.5
  qr_flutter: ^4.1.0
  quickalert: ^1.1.0
  rxdart: ^0.28.0 # TODO: Check if we can get streamed updates without this
  share_plus: ^12.0.0
  shared_preferences: ^2.5.3
  sqflite: ^2.4.2
  url_launcher: ^6.3.2
  uuid: ^4.5.1
  veilid:
    path: ../veilid/veilid-flutter
  veilid_support:
    path: packages/veilid_support
  flutter_staggered_grid_view: ^0.7.0
  http: ^1.5.0
  faker: ^2.2.0
  flutter_local_notifications: ^19.4.2
  phone_numbers_parser: ^9.0.15
  badges: ^3.1.2
  http_cache_file_store: ^2.0.1
  # TODO: Switch back to release once this is resolved: https://github.com/KasemJaffer/receive_sharing_intent/issues/344
  receive_sharing_intent:
    git:
      url: https://github.com/KasemJaffer/receive_sharing_intent
      ref: 2cea396843cd3ab1b5ec4334be4233864637874e
  # TODO: Switch to official release once https://github.com/builttoroam/device_calendar/pull/590 is in
  device_calendar:
    git: https://github.com/bardram/device_calendar
  file_picker: ^10.3.3
  maplibre_gl: ^0.24.0
  multiple_result: ^5.2.0
  xterm: ^4.0.0
  animated_custom_dropdown: ^3.1.1
  synchronized: ^3.4.0
  pointycastle: ^4.0.0
  hive_ce: ^2.19.1
  hive_ce_flutter: ^2.3.4
  flutter_secure_storage: ^10.0.0
  vodozemac: ^0.4.0
  flutter_vodozemac: ^0.4.1

dev_dependencies:
  bloc_test: ^10.0.0
  build_runner: ^2.7.1
  dart_pubspec_licenses: ^3.0.15
  flutter_test:
    sdk: flutter
  freezed: ^3.0.0
  icons_launcher: ^2.1.3
  integration_test:
    sdk: flutter
  json_serializable: ^6.11.1
  test: ^1.25.15
  yaml: ^3.1.3
  veilid_test:
    path: ../veilid/veilid-flutter/packages/veilid_test
  async_tools: ^0.1.10

flutter_native_splash:
  color: "#8588D0"

icons_launcher:
  image_path: 'assets/launcher/ic_logo_radius.png'
  platforms:
    web:
      enable: true
    android:
      enable: true
      image_path: 'assets/launcher/ic_logo_radius.png'
      notification_image: 'assets/launcher/ic_foreground.png'
      adaptive_background_color: '#f7f7f9'
      # adaptive_background_image: 'assets/launcher/ic_background.png'
      adaptive_foreground_image: 'assets/launcher/ic_foreground.png'
      adaptive_round_image: 'assets/launcher/ic_logo_round.png'
      adaptive_monochrome_image: 'assets/launcher/ic_black_white.png'
    ios:
      enable: true
      image_path: 'assets/launcher/ic_logo_rectangle_light.png'
      # For iOS 18+ (support dark and tinted)
      dark_path: 'assets/launcher/ic_logo_rectangle_dark.png'
      tinted_path: 'assets/launcher/ic_logo_rectangle_tinted.png'

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/icon.svg
    - assets/images/icon.png
    - assets/map-style-dataviz-black.json
    - assets/map-style-dataviz-white.json
